name: Nightly Build and Push

on:
  # schedule:
  #   - cron: 0 8 * * * 
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
  
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure environment variables
        run:
          cp .env.example .env

      - name: Run tests
        run: |
          pip install pytest
          pytest src/tests/

      - name: Send Notification Email
        if: failure()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: lance.kerluke25@ethereal.email
          password: gwS2TDkN6W2TpvBJAQ
          subject: "Nightly Build Failed"
          to: hliu93@dons.usfca.edu
          from: "GitHub Actions <no-reply@github.com>"
          body: The nightly build failed. Please check the logs for details.
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
