name: PR Check

on:
  pull_request:
    branches: 
      - main

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Conventional Commits
        uses: webiny/action-conventional-commits@v1.3.0

      - name: Close PR on failure
        if: failure()
        uses: peter-evans/close-pull@v3
        with:
          token: ${{ secrets.MYTOKEN }}
          comment: Auto-closing pull request

      - name: Send Notification Email
        if: failure()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: lance.kerluke25@ethereal.email
          password: gwS2TDkN6W2TpvBJAQ
          subject: "PR Closed: Commit message format incorrect"
          to: hliu93@dons.usfca.edu
          from: "GitHub Actions <no-reply@github.com>"
          body: Your PR was closed because it did not follow Conventional Commit standards. Please update your commit messages.
