name: PR Check

on:
  pull_request:
    branches: 
      - main

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Conventional Commits
        uses: webiny/action-conventional-commits@v1.3.0

      - name: Close PR on failure
        if: failure()
        uses: peter-evans/close-pull@v3
        with:
          token: ${{ secrets.MYTOKEN }}
          comment: Auto-closing pull request

      - name: Send Notification Email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          from: "GitHub Actions"
          to: ${{ secrets.EMAIL_TO }}
          subject: "PR Closed: Commit message format incorrect"
          body: "Your PR was closed because it did not follow Conventional Commit standards. Please update your commit messages."
